### ISSUE TITLE
Can't change item count in shopping cart

### ISSUE THREAD

**Issue by Cpidar** [aexol-studio/vendure-nextjs-storefront#31]
hello
I'm running your code and at the shopping cart drawer,  when I want change the quantities the item from the cart, I get the error below, While this problem does not exist on [https://shop.aexol.com](https://shop.aexol.com).
please help me
thanks.

```
Error
    at eval (client.ts:59:27)
    at async setItemQuantityInCart (cart.ts:102:41)
```
```
{
    "errors": [
        {
            "message": "This order does not contain an OrderLine with the id 893",
            "locations": [
                {
                    "line": 1,
                    "column": 12
                }
            ],
            "path": [
                "adjustOrderLine"
            ],
            "extensions": {
                "code": "USER_INPUT_ERROR"
            }
        }
    ],
    "data": null
}
```

**Comment by AleksanderBondar** [comment]
Added into README, as core installation steps :)
